// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package powerwall


import "github.com/seldonsmule/logmsg"

func (pP *Powerwall) GetCustomer() (bool, Customer){

  var s Customer

  pP.SetObject(&s)

  if(!pP.GetStruct("customer", false)){
    logmsg.Print(logmsg.Error, "GetStruct(customer) failed")
    return false, s
  }

  return true, s

}


type Customer struct {
	GridServices    bool `json:"grid_services"`
	LimitedWarranty bool `json:"limited_warranty"`
	Marketing       bool `json:"marketing"`
	PrivacyNotice   bool `json:"privacy_notice"`
	Registered      bool `json:"registered"`
}
