// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package powerwall


import "github.com/seldonsmule/logmsg"

func (pP *Powerwall) GetDisconnectTypes() (bool, DisconnectTypes){

  var s DisconnectTypes

  pP.SetObject(&s)

  if(!pP.GetStruct("generatorsdisconnecttypes", false)){
    logmsg.Print(logmsg.Error, "GetStruct(generatorsdisconnecttypes) failed")
    return false, s
  }

  return true, s

}


type DisconnectTypes []string
