// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package powerwall


import "github.com/seldonsmule/logmsg"

func (pP *Powerwall) GetGenerators() (bool, Generators){

  var s Generators

  pP.SetObject(&s)

  if(!pP.GetStruct("generators", false)){
    logmsg.Print(logmsg.Error, "GetStruct(generators) failed")
    return false, s
  }

  return true, s

}


type Generators struct {
	DisconnectType string `json:"disconnect_type"`
}
