// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package powerwall


import "github.com/seldonsmule/logmsg"

func (pP *Powerwall) GetInstaller() (bool, Installer){

  var s Installer

  pP.SetObject(&s)

  if(!pP.GetStruct("installer", false)){
    logmsg.Print(logmsg.Error, "GetStruct(installer) failed")
    return false, s
  }

  return true, s

}


type Installer struct {
	BackupConfiguration      string   `json:"backup_configuration"`
	Company                  string   `json:"company"`
	CustomerID               string   `json:"customer_id"`
	Email                    string   `json:"email"`
	HasResidualCurrentDevice bool     `json:"has_residual_current_device"`
	InstallationTypes        []string `json:"installation_types"`
	Location                 string   `json:"location"`
	Mounting                 string   `json:"mounting"`
	Phone                    string   `json:"phone"`
	RunSitemaster            bool     `json:"run_sitemaster"`
	SolarInstallation        string   `json:"solar_installation"`
	SolarInstallationType    string   `json:"solar_installation_type"`
	VerifiedConfig           bool     `json:"verified_config"`
	Wiring                   string   `json:"wiring"`
}
