// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package powerwall


import "github.com/seldonsmule/logmsg"

func (pP *Powerwall) GetInstallerCompanies() (bool, InstallerCompanies){

  var s InstallerCompanies

  pP.SetObject(&s)

  if(!pP.GetStruct("installercompanies", false)){
    logmsg.Print(logmsg.Error, "GetStruct(installercompanies) failed")
    return false, s
  }

  return true, s

}


type InstallerCompanies []struct {
	Company    string `json:"company"`
	CustomerID string `json:"customer_id"`
}
