// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package powerwall


import "github.com/seldonsmule/logmsg"

func (pP *Powerwall) GetSystemStatusSoe() (bool, SystemStatusSoe){

  var s SystemStatusSoe

  pP.SetObject(&s)

  if(!pP.GetStruct("system_status_soe", false)){
    logmsg.Print(logmsg.Error, "GetStruct(system_status_soe) failed")
    return false, s
  }

  return true, s

}


type SystemStatusSoe struct {
	Percentage float64 `json:"percentage"`
}
