// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package powerwall


import "github.com/seldonsmule/logmsg"

func (pP *Powerwall) GetSystemStatusGridfaults() (bool, SystemStatusGridfaults){

  var s SystemStatusGridfaults

  pP.SetObject(&s)

  if(!pP.GetStruct("system_status_gridfaults", false)){
    logmsg.Print(logmsg.Error, "GetStruct(system_status_gridfaults) failed")
    return false, s
  }

  return true, s

}


type SystemStatusGridfaults []interface{}
