// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package main

type PW_InstallerCompanies []struct {
	Company    string `json:"company"`
	CustomerID string `json:"customer_id"`
}
