// This file was autogenerated using https://github.com/twpayne/go-jsonstruct

package powerwall

import (
	"time"
)


import "github.com/seldonsmule/logmsg"

func (pP *Powerwall) GetLogin() (bool, Login){

  var s Login

  pP.SetObject(&s)

  if(!pP.GetStruct("login", false)){
    logmsg.Print(logmsg.Error, "GetStruct(login) failed")
    return false, s
  }

  return true, s

}


type Login struct {
	Email     string    `json:"email"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	LoginTime time.Time `json:"loginTime"`
	Provider  string    `json:"provider"`
	Roles     []string  `json:"roles"`
	Token     string    `json:"token"`
}
